const Errors = {
    playerExists: 'player exists',
    playerNotFound: 'player not found',
    gameNotFound: 'game not found',
    monsterInstanceNotFound: 'monster instance not found',
    playerNotInGame: 'Player not in game',
    battleNotFound: 'Battle not found',
    weaponNotInBag: 'Weapon not in bag',
    bookNotInBag: 'Book not in bag',
    badAbilityBookIndex: 'Ability book index out of range',
    abilityNotFound: 'Ability not found',
    itemNotinBag: 'Item not in bag',
    abilitiesFull: 'Player ability slots are full',
    abilityRequirementNotMet: 'The requirements to equip this ability were not met',
    abilityNotEquipped: 'This ability is not equipped',
    itemNotEquipped: 'This item is not equipped',
    notEnoughAp: 'Not enough ap to use this ability',
    shopNotFound: 'Shop not found',
    productNotFound: 'Product not found',
    insufficientFunds: 'Insufficient funds',
    objectNotInBag: 'Object not found in bag',
    inventoryPageNotFound: 'Inventory page not found',
    objectNotInInventory: 'Object not found in inventory',
    objectCantBeclaimed: 'Object cannot be claimed',
    unrecognizedItemType: 'Unrecognized item type',
    productSkuNotFound: 'Product SKU not found',
    bagFull: 'The player\'s bag is full',
    objectNotFound: 'Object not found',
    insufficientObjectStackSize: 'Not enough copies of the object are owned',
    invalidParams: 'The parameter passed were invalid'
}

module.exports = Errors;